- hosts: aws
  user: ec2-user
  vars_files:
    - vars/env.yml
    - vars/private.yml
  tasks:
    - git: repo=https://github.com/osamunmun/hubot.git dest=/home/ec2-user/hubot accept_hostkey=yes
    - file: path=/home/ec2-user/cache state=directory
    - shell: cd /home/ec2-user/hubot; sudo ./docker-build.sh
    - shell: sudo docker stop $(sudo docker ps -a -q)
    - shell: cd /home/ec2-user/hubot; sudo docker run -e HUBOT_STAMPS={{ HUBOT_STAMPS }} -e HUBOT_SLACK_TOKEN={{ HUBOT_SLACK_TOKEN }} -e HUBOT_SLACK_TEAM={{ HUBOT_SLACK_TEAM }} -d -v $(pwd):/hubot hubot/slack
